### ISSUE TITLE
Compilation during `make` fails

### ISSUE THREAD

**Issue by NavneelSinghal** [Lixxia/i3lock#22]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Running `make` leads to a compilation error (due to multiple definitions of the variable `input_position`).

## Expected Behavior

Compilation should complete without errors.

## Resolution of the bug
Just commenting out the line `int input_position;` (or making the variable `extern`) in the file `unlock_indicator.c` works. Putting this bugfix out there so that people can resolve this error on their own.

## Reproduction Instructions

Identical to the installation instructions on a fresh clone of the repo.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version be2a08a (2019-10-05, branch "master") © 2010 Michael Stapelberg
</pre>

**Comment by shgninc** [comment]
> ## Resolution of the bug
> 
> Just commenting out the line `int input_position;` (or making the variable `extern`) in the file `unlock_indicator.c` works. Putting this bugfix out there so that people can resolve this error on their own.

I have the same problem, after i upgrade debian 10 to 11.

Thanks to @NavneelSinghal, This answer work for me.

**Comment by matteodiga** [comment]
Same problem, same solution! Thanks
